name: Build and deploy Python app to Azure Web App - Object-Detection-Web-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'
      
      - name: Install system dependencies
        run: sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Prepare deployment content
        run: |
          cp requirements.txt ./artifact/
          cp app.py ./artifact/
          # Include other necessary files for deployment here
          echo '#!/bin/bash' > artifact/startup.sh
          echo 'apt-get update && apt-get install -y libjpeg62 libjpeg62-dev' >> artifact/startup.sh
          echo 'gunicorn --bind 0.0.0.0:8000 app:app' >> artifact/startup.sh
          chmod +x artifact/startup.sh

      - name: Zip artifact for deployment
        run: zip release.zip artifact/* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Object-Detection-Web-App'
          slot-name: 'Production'
          startup-command: '/home/site/wwwroot/artifact/startup.sh'
